# .github/workflows/terraform-plan.yml
name: "Terraform — Plan (PR)"

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write        # required for OIDC tokens
  pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}   # recommended
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform fmt & validate
        run: |
          terraform fmt -check
          terraform validate -no-color

      - name: Terraform plan (write tfplan & human text)
        run: |
          terraform plan -no-color -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.sha }}
          path: |
            tfplan
            plan.txt
