# .github/workflows/terraform-destroy.yml
name: "Terraform — Destroy (manual)"

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type YES to confirm destroy'
        required: true
        default: 'no'

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    if: ${{ github.event.inputs.confirm_destroy == 'YES' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
            
      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform destroy (confirmed)
        run: terraform destroy -auto-approve -no-color
